# Generated by Django 2.1.5 on 2019-02-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginandregister',
            name='reenter_password',
        ),
    ]
